### ISSUE TITLE
Emails Content 

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/voicesky#21]

**Comment by ZarshaB** [comment]
1>>   Order Confirmation:

Subject: Your Order is Confirmed. 

Hi Tahir,
Thank you for shopping with us! We have received you order successfully. Here are your updated account details:
**Order Id**: kqzg2c7f
**Amount**: €10.00
**Status**: AUTHORIZED
**Payment Method**: Visa **** **** **** 9696 (Expiry 06/2021) 
**Previous Balance**: $5.00
**Current Balance**: $3.00

In order to see your payment history or request an invoice go to **Billing & payments** in Dashboard.

Regards,
The VoiceSky Team

**Comment by ZarshaB** [comment]
2>> Verify Email

Subject: Verify your Email.

Hi Tahir,
Thanks for joining us!
To access your account please verify your email address.
 
**Verify Email address**

Regards,
The VoiceSky Team

**Comment by ZarshaB** [comment]
3>> Welcome Email

Subject: Welcome to VoiceSky

Thank you for becoming part of VoiceSky. 

Regards,
The VoiceSky Team

**Comment by ZarshaB** [comment]
4>>(Valid 60 minutes)
 Forgot Password:
Subject: Password Reset Request

Hi Tahir,
Forgot your password? Don’t worry it happens to all of us. 
We are here for you to help. 
**Reset Password**
 
Regards,
The VoiceSky Team

**Comment by ZarshaB** [comment]
5>> Reset Password:
Subject: Your Password has been Reset. 

Hi Tahir,
Your Password has been reset. 

Regards,
The VoiceSky Team

**Comment by ZarshaB** [comment]
6>> Account Status 
Subject: Account status Update

Hi Tahir,
Your account status has been updated and it's in "In Process" state now. Please contact support for more info.

Regards,
The VoiceSky Team

**Comment by ZarshaB** [comment]
6>> These are not linked.
![image](https://user-images.githubusercontent.com/35685146/56198094-a3e8b600-6053-11e9-9a38-3b566b572a31.png)
![image](https://user-images.githubusercontent.com/35685146/56198106-ac40f100-6053-11e9-9f46-c51ec25895a8.png)

**Comment by ZarshaB** [comment]
7>> Link should expire once I have reset password. And also there should be time limit for password reset link to expire. 
![image](https://user-images.githubusercontent.com/35685146/56197718-d645e380-6052-11e9-8d16-0e62bd00f565.png)

**Comment by ZarshaB** [comment]
8>> Please add this line for all emails footer below:
Regards,
The Voicesky Team
VoiceSky is a cloud communications platform for developing Two Factor Authentication and Number Masking.

**Comment by sammiullah** [comment]
**All above issue are fixed, Please test and remove those are fixed.**

**Comment by ZarshaB** [comment]
3>> Please remove the highlighted portion.
And please make whole email with the same font. 
![image](https://user-images.githubusercontent.com/35685146/56223893-11163e80-6088-11e9-944e-7ed20b8beb6e.png)

**Comment by ZarshaB** [comment]
**I didn't get this email.** 
 2>> Verify Email

Subject: Activate your Account

Hi Tahir,

Regards,
The VoiceSky Team
VoiceSky is a cloud communications platform for developing Two Factor Authentication and  Number Masking. 

![image](https://user-images.githubusercontent.com/35685146/56127482-b224cc80-5f96-11e9-8af9-15dac807334a.png)
![image](https://user-images.githubusercontent.com/35685146/56127499-b94bda80-5f96-11e9-8ac4-7d2d9102ea11.png)

**Comment by ZarshaB** [comment]
**Not fixed.** 
6>> These are not linked.
![image](https://user-images.githubusercontent.com/35685146/56198094-a3e8b600-6053-11e9-9a38-3b566b572a31.png)
![image](https://user-images.githubusercontent.com/35685146/56198106-ac40f100-6053-11e9-9f46-c51ec25895a8.png)

**Comment by ZarshaB** [comment]
**Not fixed**
8>> Please add this line for all emails footer below:
Regards,
The Voicesky Team
VoiceSky is a cloud communications platform for developing Two Factor Authentication and Number Masking.
