### ISSUE TITLE
Admin Issues 27-11-2018

### ISSUE THREAD

**Issue by ZarshaB** [asifjans/voicesky#7]

**Comment by ZarshaB** [comment]
1>> Forgot Password link is not working and it should be in line with Remember Me. 
And Register Now option is not required so you can remove it.
![image](https://user-images.githubusercontent.com/35685146/49085216-52da5000-f273-11e8-8ca6-bbbbd0f14a82.png)

**Comment by ZarshaB** [comment]
2>> Icons of these headings should be different.
![image](https://user-images.githubusercontent.com/35685146/49085289-80bf9480-f273-11e8-8016-f17c21ac706a.png)

**Comment by ZarshaB** [comment]
3>> Please reduce the size of buttons and make it equal in size.
![image](https://user-images.githubusercontent.com/35685146/49085540-0f341600-f274-11e8-8df1-5154005212da.png)
![image](https://user-images.githubusercontent.com/35685146/49085627-41457800-f274-11e8-91a8-175a0b674b41.png)

**Comment by ZarshaB** [comment]
4>> Clicking on any option from it redirects to error page.
![image](https://user-images.githubusercontent.com/35685146/49085806-b3b65800-f274-11e8-9ec5-90ce84e67a10.png)

![image](https://user-images.githubusercontent.com/35685146/49085770-a00af180-f274-11e8-9c37-c7b2f7d59cce.png)

**Comment by ZarshaB** [comment]
5>> It is update settings page but displaying heading of DID.
![image](https://user-images.githubusercontent.com/35685146/49085881-e6f8e700-f274-11e8-8c92-d7840d4bae40.png)

**Comment by ZarshaB** [comment]
6>> On clicking on Dashboard it redirects to error page.
![image](https://user-images.githubusercontent.com/35685146/49085905-f841f380-f274-11e8-919e-a1b04f64c94b.png)
![image](https://user-images.githubusercontent.com/35685146/49085916-01cb5b80-f275-11e8-9a13-47289588b81f.png)

**Comment by ZarshaB** [comment]
7>> Link of Inovedia site should be opened in next tab. And there should be double colon (:) after Designed By:
![image](https://user-images.githubusercontent.com/35685146/49086851-553ea900-f277-11e8-8244-1c5a0cb07bdd.png)

**Comment by ZarshaB** [comment]
8>> Please make R capital for both Rights and Reserved.
![image](https://user-images.githubusercontent.com/35685146/49086885-6d162d00-f277-11e8-9101-9a6e3f772631.png)

**Comment by ZarshaB** [comment]
9>> There should be confirmation before submitting form.
![image](https://user-images.githubusercontent.com/35685146/49086926-8a4afb80-f277-11e8-85be-e8b3dc1ec552.png)

**Comment by ZarshaB** [comment]
10>> Also put some notes for it to explain. On this page. 
![image](https://user-images.githubusercontent.com/35685146/49087069-da29c280-f277-11e8-96c1-022a8b3a7cd6.png)

**Comment by ZarshaB** [comment]
11>> Please make it to two decimal places. And also mention it's unit whether it is in dollar or any other unit.
![image](https://user-images.githubusercontent.com/35685146/49087572-21fd1980-f279-11e8-9b64-2ce5dde70199.png)

**Comment by ZarshaB** [comment]
12>> These pop up text font is very large.
![image](https://user-images.githubusercontent.com/35685146/49087772-a780c980-f279-11e8-817b-590ffd3adabd.png)

**Comment by ZarshaB** [comment]
13>> Please make it to suspended.
![image](https://user-images.githubusercontent.com/35685146/49087796-b5364f00-f279-11e8-8570-81cf0b6a419f.png)

**Comment by ZarshaB** [comment]
14>> Voicesky and Inovedia should be bold or in different colors so that it could be recognized as colors. 
![image](https://user-images.githubusercontent.com/35685146/49088797-dd26b200-f27b-11e8-93bc-cb30368f247d.png)

**Comment by ZarshaB** [comment]
15>> As per discussion with management dashboard is empty right now so after login user should be redirected to this page instead of dashboard. 
![image](https://user-images.githubusercontent.com/35685146/49090352-596ec480-f27f-11e8-8b8e-d139f3d9d128.png)

**Comment by ZarshaB** [comment]
16>> It does not have equal spacing.
![image](https://user-images.githubusercontent.com/35685146/46140781-78df7600-c26b-11e8-987d-f0b995c03a38.png)

**Comment by ZarshaB** [comment]
17>> It should display message:
"This field is required."
![image](https://user-images.githubusercontent.com/35685146/49143223-68578480-f31c-11e8-8ccb-17fcebcc6adf.png)

**Comment by sammiullah** [comment]
**All the issues are Fixed**

**Comment by ZarshaB** [comment]
17>> Other validations are okay now but Please also change this message with the one we have for login of user site.
![image](https://user-images.githubusercontent.com/35685146/49291202-4d774280-f4cb-11e8-938d-b8f335947081.png)
![image](https://user-images.githubusercontent.com/35685146/49291217-5ff17c00-f4cb-11e8-8dbe-b8885526eca3.png)

**Comment by ZarshaB** [comment]
**Reopened**
3>> Button size still look same big.

**Comment by ZarshaB** [comment]
**Reopened**
10>> 
16>> Headings still do not have equal spacing. Sir Asif said that these tables could be replaced with some other tables.

**Comment by ZarshaB** [comment]
18>> Please change the color of links (Inovedia, Voicesky) to white but make them bold. As yellow color is not looking so appealing.
![image](https://user-images.githubusercontent.com/35685146/49292452-1acf4900-f4cf-11e8-8e61-4bb3a07c4551.png)
